[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja"
]
build-backend = "setuptools.build_meta"

[project]
name = "camera-pipeline-processor"
version = "0.1.0"
description = "A camera pipeline processor for video processing."
authors = [
    { name="Leandro Zanatta", email="leandro@example.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "opencv-python==4.11.0.86"
]

[project.urls]
"Homepage" = "https://github.com/leandroZanatta/camera-pipeline"

[project.optional-dependencies]
numpy = ["numpy>=1.26.4"]
ui = ["PySide6>=6.5.0"]
dev = ["pytest>=7.4.2", "black>=23.9.1"]
full = ["numpy>=1.26.4", "PySide6>=6.5.0", "pytest>=7.4.2", "black>=23.9.1"]

[tool.setuptools.packages.find]

[tool.cmake]
minimum-version = "3.10"

[tool.cmake.build]
config = "Release"

[tool.cmake.find]
find_package = "FFmpeg" 