[build-system]
requires = [
    "setuptools>=78.1.0",
    "wheel>=0.44.0",
    "scikit-build>=0.18.1",
    "packaging>=24.2",
    "distro>=1.9.0",
    "cmake>=3.10.0",
    "ninja",
]
build-backend = "setuptools.build_meta"

[project]
name = "camera-pipeline-processor"
version = "0.1.0"
description = "Processador de Pipeline de Câmera com C/C++ e Python"
readme = "README.md"
authors = [
    {name = "Leandro", email = "leandrozanatta27@gmail.com"},
]
requires-python = ">=3.8"
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: C",
]
dependencies = [
    "opencv-python==4.11.0.86",
]

[project.optional-dependencies]
numpy = ["numpy>=1.26.4"]
ui = ["PySide6"]
dev = ["pytest", "black", "flake8"]
test = ["pytest"]
full = ["numpy>=1.26.4", "PySide6"]

[project.urls]
Homepage = "https://github.com/leandroZanatta/camera-pipeline"
Repository = "https://github.com/leandroZanatta/camera-pipeline.git"

[tool.setuptools]
packages = ["camera_pipeline", "camera_pipeline.core"]
package-data = {camera_pipeline = ["core/*.so", "core/*.dll", "core/camera_processor/*.so", "core/camera_processor/*.dll"]}
include-package-data = true

[tool.scikit-build]
cmake.source-dir = "c_src"
cmake.install-dir = "camera_pipeline/core/camera_processor"
cmake.build-type = "Release"
cmake.verbose = true
wheel.expand-macos-universal-tags = true 